// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs8m2Wg3uqjpoCQI0kHg5VR0NmIlL6OYA',
    appId: '1:154669847527:web:76066b63613efa7540a342',
    messagingSenderId: '154669847527',
    projectId: 'mantenimientotoner',
    authDomain: 'mantenimientotoner.firebaseapp.com',
    storageBucket: 'mantenimientotoner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnUwrCQiTuSe3D1NhVRP9lX45ySHl2VfM',
    appId: '1:154669847527:android:0ebc8e29df391b1b40a342',
    messagingSenderId: '154669847527',
    projectId: 'mantenimientotoner',
    storageBucket: 'mantenimientotoner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOOrB8Hg9veSOqGncByI053zykgZd5nBE',
    appId: '1:154669847527:ios:8d99985ec8ec0c8a40a342',
    messagingSenderId: '154669847527',
    projectId: 'mantenimientotoner',
    storageBucket: 'mantenimientotoner.firebasestorage.app',
    iosBundleId: 'com.example.mantenimientoToner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOOrB8Hg9veSOqGncByI053zykgZd5nBE',
    appId: '1:154669847527:ios:8d99985ec8ec0c8a40a342',
    messagingSenderId: '154669847527',
    projectId: 'mantenimientotoner',
    storageBucket: 'mantenimientotoner.firebasestorage.app',
    iosBundleId: 'com.example.mantenimientoToner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs8m2Wg3uqjpoCQI0kHg5VR0NmIlL6OYA',
    appId: '1:154669847527:web:436d75132226c43240a342',
    messagingSenderId: '154669847527',
    projectId: 'mantenimientotoner',
    authDomain: 'mantenimientotoner.firebaseapp.com',
    storageBucket: 'mantenimientotoner.firebasestorage.app',
  );
}
